CREATE TABLE projetoenergiza.dbo.DOCUMENTOS (
	ID_DOCUMENTO int IDENTITY(1,1) NOT NULL,
	ID_PESSOAS_FJ int NOT NULL,
	NUMERO varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	DOCUMENTO_IMAGEM varbinary(MAX) NULL,
	CONSTRAINT PK__DOCUMENT__DD20AF840AB25B90 PRIMARY KEY (ID_DOCUMENTO)
);