CREATE TABLE projetoenergiza.dbo.FATURA (
	ID_FATURA int IDENTITY(1,1) NOT NULL,
	REFERENCIA varchar(7) COLLATE Latin1_General_CI_AS NOT NULL,
	VENCIMENTO date NOT NULL,
	ID_UNIDADE_CONSUMO int NOT NULL,
	VALOR_TOTAL decimal(38,0) NOT NULL,
	CONSTRAINT PK__FATURA__B6A3888883D4E223 PRIMARY KEY (ID_FATURA)
);