CREATE TABLE projetoenergiza.dbo.FT_ITENS_FATURA (
	ID_FT_ITENS_FATURA int IDENTITY(1,1) NOT NULL,
	ITEM varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	UNIDADE varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
	QUANTIDADE decimal(18,2) NOT NULL,
	VALOR decimal(18,2) NOT NULL,
	ID_FATURA int NOT NULL,
	CONSTRAINT PK__FT_ITENS__3B67F3CC93D2ADFC PRIMARY KEY (ID_FT_ITENS_FATURA)
);