CREATE TABLE projetoenergiza.dbo.FT_LEITURA (
	ID_FT_LEITURA int IDENTITY(1,1) NOT NULL,
	DATA_LEITURA_ANTERIOR date NOT NULL,
	DATA_LEITURA_ATUAL date NOT NULL,
	DATA_LEITURA_PROXIMA date NOT NULL,
	DIAS_LIDOS int NOT NULL,
	MEDIDOR varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	LEITURA_ANTERIOR decimal(18,3) NOT NULL,
	LEITURA_ATUAL decimal(18,3) NOT NULL,
	TOTAL_APURADO decimal(18,3) NOT NULL,
	ID_FATURA int NOT NULL,
	SERVICO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT PK__FT_LEITU__59363205CC7D6D09 PRIMARY KEY (ID_FT_LEITURA)
);