CREATE TABLE projetoenergiza.dbo.IDENTIFICACAO (
	ID_IDENTIFICACAO int IDENTITY(1,1) NOT NULL,
	ID_PESSOAS_FJ int NOT NULL,
	NOME varchar(200) COLLATE Latin1_General_CI_AS NOT NULL,
	APELIDO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	IMAGEM varbinary(MAX) NULL,
	CONSTRAINT PK__IDENTIFI__CDBCD2F90DF3BEA4 PRIMARY KEY (ID_IDENTIFICACAO)
);