CREATE TABLE projetoenergiza.dbo.LOCALIZACAO (
	ID_LOCALIZACAO int IDENTITY(1,1) NOT NULL,
	ID_PESSOAS_FJ int NULL,
	CEP varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
	ENDERECO varchar(200) COLLATE Latin1_General_CI_AS NOT NULL,
	NUMERO varchar(10) COLLATE Latin1_General_CI_AS NULL,
	COMPLEMENTO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	BAIRRO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	CIDADE varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	ESTADO varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	PAIS varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	ID_UNIDADE_CONSUMO int NULL,
	CONSTRAINT PK__LOCALIZA__9BFA9159BB9F6AAA PRIMARY KEY (ID_LOCALIZACAO)
);