CREATE TABLE projetoenergiza.dbo.OPERADOR_ENERGETICO (
	ID_OPERADOR_ENERGETICO int IDENTITY(1,1) NOT NULL,
	ID_IDENTIFICACAO int NULL,
	ID_DOCUMENTO int NULL,
	CONSTRAINT PK__OPERADOR__BD4A96B7329C0EB2 PRIMARY KEY (ID_OPERADOR_ENERGETICO)
);