CREATE TABLE projetoenergiza.dbo.PESSOAS_FJ (
	ID_PESSOAS_FJ int IDENTITY(1,1) NOT NULL,
	APELIDO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	TIPO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	ID_ENDERECO int NULL,
	ID_DOCUMENTO int NULL,
	ID_IDENTIFICACAO int NULL,
	ID_REDES_SOCIAIS int NULL,
	ID_OPERADOR_ENERGETICO int NULL,
	CONSTRAINT PK__PESSOASF__E32DFB820166296A PRIMARY KEY (ID_PESSOAS_FJ)
);