CREATE TABLE projetoenergiza.dbo.PESSOAS_FJ (
	ID_PESSOAS_FJ int IDENTITY(1,1) NOT NULL,
	APELIDO varchar(100) COLLATE Latin1_General_CI_AS NULL,
	CONSTRAINT PK__PESSOASF__E32DFB820166296A PRIMARY KEY (ID_PESSOAS_FJ)
);