CREATE TABLE projetoenergiza.dbo.REDES_SOCIAIS (
	ID_REDE_SOCIAL int IDENTITY(1,1) NOT NULL,
	ID_PESSOAS_FJ int NOT NULL,
	PLATAFORMA varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	TELEFONE varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	URL varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT PK__REDES_SO__B06B9C17701E761A PRIMARY KEY (ID_REDE_SOCIAL)
);