CREATE TABLE projetoenergiza.dbo.SENHA_TOKEN (
	ID int IDENTITY(1,1) NOT NULL,
	EMAIL varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	TOKEN varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	EXPIRACAO datetime NOT NULL,
	CONSTRAINT PK__senhaTok__3213E83F17824E51 PRIMARY KEY (ID)
);