CREATE TABLE projetoenergiza.dbo.UC_CLIENTES (
	ID_UC_CLIENTES int IDENTITY(1,1) NOT NULL,
	IDENTIFICACAO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CODIGO int NULL,
	CONSTRAINT PK__CONSUMID__631BC4F46480943E PRIMARY KEY (ID_UC_CLIENTES)
);