CREATE TABLE projetoenergiza.dbo.UC_CONFIGURACAO (
	ID_UC_CONFIGURACAO int IDENTITY(1,1) NOT NULL,
	ID_TIP_GRUPO_TARIFARIO int NOT NULL,
	ID_TIP_SUBGRUPO_TARIFARIO int NOT NULL,
	ID_TIP_MODALIDADE_TARIFARIA int NOT NULL,
	ID_TIP_CLASSIFICACAO_IMOVEL int NOT NULL,
	ID_TIP_TIPO_FORNECIMENTO int NOT NULL,
	ID_TIP_ORIGEM_LEITURA int NOT NULL,
	CONSTRAINT PK__CONFIGUR__83C33A77EE4B272B PRIMARY KEY (ID_UC_CONFIGURACAO)
);