CREATE TABLE projetoenergiza.dbo.UC_DISTRIBUICAO_ENERGETICA (
	ID_UC_DISTRIBUICAO_ENERGETICA int IDENTITY(1,1) NOT NULL,
	PERCENTUAL_DIST_ATUAL decimal(5,2) NULL,
	PERCENTUAL_DIST_ANTERIOR decimal(5,2) NULL,
	ID_UC_USINAS int NOT NULL,
	ID_UC_CONSUMIDORES int NOT NULL,
	CONSTRAINT PK__UC_DISTR__2A6A94E800614EEB PRIMARY KEY (ID_UC_DISTRIBUICAO_ENERGETICA)
);