CREATE TABLE projetoenergiza.dbo.UC_DISTRIBUIDORA (
	ID_UC_DISTRIBUIDORA int IDENTITY(1,1) NOT NULL,
	NOME varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	CONSTRAINT PK__UC_DISTR__092214A3B53C5CFA PRIMARY KEY (ID_UC_DISTRIBUIDORA)
);