CREATE TABLE projetoenergiza.dbo.UC_ENDERECO (
	ID_UC_ENDERECO int IDENTITY(1,1) NOT NULL,
	CEP varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
	ENDERECO varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	NUMERO varchar(10) COLLATE Latin1_General_CI_AS NOT NULL,
	COMPLEMENTO varchar(255) COLLATE Latin1_General_CI_AS NULL,
	REFERENCIA varchar(255) COLLATE Latin1_General_CI_AS NULL,
	BAIRRO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	CODIGO_POSTAL varchar(20) COLLATE Latin1_General_CI_AS NULL,
	CIDADE varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	ESTADO varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	PAIS varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	LOCALIZACAO geography NULL,
	CONSTRAINT PK__UC_ENDER__2D26A3EB32F7D7EE PRIMARY KEY (ID_UC_ENDERECO)
);