CREATE TABLE projetoenergiza.dbo.UC_PLANEJ_KWH_MES (
	ID_UC_PLANEJ_KWH_MES int IDENTITY(1,1) NOT NULL,
	MES_ANO date NULL,
	KWH_PROJETADO decimal(10,2) NULL,
	ID_UC_USINAS int NOT NULL,
	ID_UC_CLIENTES int NOT NULL,
	CONSTRAINT PK__UC_PLANE__CACDEAB05D88FF7A PRIMARY KEY (ID_UC_PLANEJ_KWH_MES)
);