CREATE TABLE projetoenergiza.dbo.UC_USINAS (
	ID_UC_USINAS int IDENTITY(1,1) NOT NULL,
	IDENTIFICACAO varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	PERC_PERDA_MES decimal(5,2) NULL,
	ID_UNIDADE_CONSUMO int NOT NULL,
	CONSTRAINT PK__USINAS__3214EC27B35808A2 PRIMARY KEY (ID_UC_USINAS)
);