CREATE TABLE projetoenergiza.dbo.UNIDADE_CONSUMO (
	ID_UNIDADE_CONSUMO int IDENTITY(1,1) NOT NULL,
	ID_OPERADOR_ENERGETICO int NULL,
	UC_CODIGO varchar(50) COLLATE Latin1_General_CI_AS NOT NULL,
	EH_GERADORA bit NULL,
	ID_UC_DISTRIBUIDORA int NOT NULL,
	ID_PESSOA_FJ_PROPRIETARIO int NOT NULL,
	ID_UC_CONFIGURACAO int NULL,
	ID_ENDERECO int NOT NULL,
	MEDIDOR varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	ID_UC_CLIENTES int NULL,
	CONSTRAINT PK__UC_UNIDA__536346938BDF8B81 PRIMARY KEY (ID_UNIDADE_CONSUMO)
);