CREATE TABLE projetoenergiza.dbo.USER_SESSIONS (
	SESSION_ID varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	USER_ID int NOT NULL,
	LOGIN_TIME datetime NOT NULL,
	LAST_ACTIVITY datetime NOT NULL,
	IP_ADDRESS varchar(50) COLLATE Latin1_General_CI_AS NULL,
	USER_AGENT varchar(255) COLLATE Latin1_General_CI_AS NULL,
	IS_ACTIVE bit DEFAULT 1 NULL,
	CONSTRAINT PK__USER_SES__F0174874436F7CF1 PRIMARY KEY (SESSION_ID)
);