CREATE TABLE projetoenergiza.dbo.USUARIO (
	ID int IDENTITY(1,1) NOT NULL,
	NOME varchar(100) COLLATE Latin1_General_CI_AS NOT NULL,
	EMAIL varchar(150) COLLATE Latin1_General_CI_AS NOT NULL,
	SENHA_HASH varchar(255) COLLATE Latin1_General_CI_AS NOT NULL,
	WHATSAPP varchar(15) COLLATE Latin1_General_CI_AS NULL,
	TELEFONE varchar(15) COLLATE Latin1_General_CI_AS NULL,
	DH_CADASTRO datetime DEFAULT getdate() NOT NULL,
	DATA_NASCIMENTO date NULL,
	ID_PESSOA int NULL,
	CONSTRAINT PK__Usuario__3214EC27650C77FC PRIMARY KEY (ID),
	CONSTRAINT UQ__USUARIO_EMAIL UNIQUE (EMAIL)
);